name: build

env:
  IMAGE_NAME: godot-ci

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of engine to build e.g. "3.4.4", "3.5"'
        required: true
        type: string

      release_name:
        description: 'Release name, usually "stable", but can also be something like "rc3", "beta1"'
        type: string
        default: "stable"
        required: true

      godot_platform:
        description: 'Name of the Platform to download. For Godot 3.X this is linux_headless.64, while for Godot 4 it is linux.x86_64'
        type: string
        default: "linux.x86_64"
        required: true

      godot_args:
        description: 'Appends additional arguments to the Godot invocation running the container running. This allows to specify the display driver in Godot 4+. Otherwise empty'
        type: string
        default: "--display-driver headless"
        required: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: abarichello/godot-ci

      - name: 'Fork: Add fix for Godot 4'
        run: |
          REPLACE_NEEDLE=linux_headless.64
          sed -i 's/'${REPLACE_NEEDLE}'/${GODOT_PLATFORM}/g' Dockerfile
          sed -i 's/RUN godot -e -q/RUN godot -e -q ${GODOT_TEST_ARGS}/g' Dockerfile
          sed -i '/ARG SUBDIR=""/a ARG GODOT_PLATFORM="'${REPLACE_NEEDLE}'"' Dockerfile
          sed -i '/ARG SUBDIR=""/a ARG GODOT_TEST_ARGS=""' Dockerfile

      - run:  echo IMAGE_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run:  echo IMAGE_TAG=$(echo ${{ github.event.inputs.release_name != 'stable' && format('.{0}', github.event.inputs.release_name) || '' }}) >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }}${{ env.IMAGE_TAG }}
          build-args: |
            GODOT_VERSION=${{ github.event.inputs.version }}
            RELEASE_NAME=${{ github.event.inputs.release_name }}
            SUBDIR=${{  github.event.inputs.release_name != 'stable' && format('/{0}', github.event.inputs.release_name) || '' }}
            GODOT_PLATFORM=${{ github.event.inputs.godot_platform }}
            GODOT_TEST_ARGS=${{ github.event.inputs.godot_args }}
